- hosts: all
  become: true
  tasks:
   - copy:
        content: "hello world"
        dest: /tmp/amit.txt
     notify: restart httpd


  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
        enabled: yes

